# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94eb7761c9d06b8a86f9d1c58f31707ee1769072826582336348b08a6fb359e736dc63f14bf7cc17cd648fb8202bbe7457987e49525594a20152444d69dccaac

test:
  secret_key_base: f6eadf8f94a0c0e26ab882c40cedaf5a2a8fa265074b0ca6089b83f1192d8426091121f398ba13d3208342593c716db3dc08d7f15e8a0f63c846c8c6a7827975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
